### ISSUE TITLE
site template

### ISSUE THREAD

**Issue by sn0n** [blokz/gen#1]
Work on initial template

**Comment by sn0n** [comment]
started using a material gatsby project forked from 
https://github.com/Vagr9K/gatsby-material-starter
will be updating later with instructions to setup and get running locally from a clean install... as its been taking me hours to figure out whats going on with the folder structure.. finally getting it down.. it didn't help any that I wasn't learning gatsby first, i was just jumping into his project.. so took that step back,.. and working on the gatsby tutorial to fully "get" the system.. once done with the tutorial I'll come back to the material design and blokz cms. 
ref: 
https://github.com/gatsbyjs/gatsby
https://www.gatsbyjs.org/tutorial/

and huge shoutout to @Vagr9K (4chan or just a goku fan?) for starting his project.

**Comment by Vagr9K** [comment]
> and huge shoutout to @Vagr9K (4chan or just a goku fan?) for starting his project.
It's great to hear that this project is working out for you!

> 4chan or just a goku fan

It's just an Armenian word Tiger added to a random 9K, so neither of those things :)
